apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  # Secret מכיל מידע רגיש כמו סיסמאות
  # Kubernetes מצפין ומבודד את המידע הזה
type: Opaque
stringData:
  # סיסמת המשתמש הרגיל
  MYSQL_PASSWORD: password
  # סיסמת המשתמש root (מנהל)
  MYSQL_ROOT_PASSWORD: rootpassword

